In [3]:
pip install streamlit_option_menu

Requirement already satisfied: streamlit_option_menu in c:\vscode\.venv\lib\site-packages (0.3.12)
Requirement already satisfied: streamlit>=0.63 in c:\vscode\.venv\lib\site-packages (from streamlit_option_menu) (1.32.2)
Requirement already satisfied: altair<6,>=4.0 in c:\vscode\.venv\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (5.2.0)
Requirement already satisfied: blinker<2,>=1.0.0 in c:\vscode\.venv\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (1.7.0)
Requirement already satisfied: cachetools<6,>=4.0 in c:\vscode\.venv\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in c:\vscode\.venv\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (8.1.7)
Requirement already satisfied: numpy<2,>=1.19.3 in c:\vscode\.venv\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (1.26.4)
Requirement already satisfied: packaging<24,>=16.8 in c:\vscode\.venv\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (23.2)
Requirement already satisfied: pandas<3,>=1.3.0 in c:\vscode\.venv\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (2.2.1)
Requirement already satisfied: pillow<11,>=7.1.0 in c:\vscode\.venv\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (10.2.0)
Requirement already satisfied: protobuf<5,>=3.20 in c:\vscode\.venv\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (4.25.3)
Requirement already satisfied: pyarrow>=7.0 in c:\vscode\.venv\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (15.0.1)
Requirement already satisfied: requests<3,>=2.27 in c:\vscode\.venv\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (2.31.0)
Requirement already satisfied: rich<14,>=10.14.0 in c:\vscode\.venv\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (13.7.1)
Requirement already satisfied: tenacity<9,>=8.1.0 in c:\vscode\.venv\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (8.2.3)
Requirement already satisfied: toml<2,>=0.10.1 in c:\vscode\.venv\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in c:\vscode\.venv\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (4.10.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\vscode\.venv\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (3.1.42)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\vscode\.venv\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (0.8.1b0)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\vscode\.venv\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (6.4)
Requirement already satisfied: watchdog>=2.1.5 in c:\vscode\.venv\lib\site-packages (from streamlit>=0.63->streamlit_option_menu) (4.0.0)
Requirement already satisfied: jinja2 in c:\vscode\.venv\lib\site-packages (from altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (3.1.3)
Requirement already satisfied: jsonschema>=3.0 in c:\vscode\.venv\lib\site-packages (from altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (4.21.1)
Requirement already satisfied: toolz in c:\vscode\.venv\lib\site-packages (from altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (0.12.1)
Requirement already satisfied: colorama in c:\vscode\.venv\lib\site-packages (from click<9,>=7.0->streamlit>=0.63->streamlit_option_menu) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\vscode\.venv\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit>=0.63->streamlit_option_menu) (4.0.11)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\vscode\.venv\lib\site-packages (from pandas<3,>=1.3.0->streamlit>=0.63->streamlit_option_menu) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\vscode\.venv\lib\site-packages (from pandas<3,>=1.3.0->streamlit>=0.63->streamlit_option_menu) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\vscode\.venv\lib\site-packages (from pandas<3,>=1.3.0->streamlit>=0.63->streamlit_option_menu) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\vscode\.venv\lib\site-packages (from requests<3,>=2.27->streamlit>=0.63->streamlit_option_menu) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\vscode\.venv\lib\site-packages (from requests<3,>=2.27->streamlit>=0.63->streamlit_option_menu) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\vscode\.venv\lib\site-packages (from requests<3,>=2.27->streamlit>=0.63->streamlit_option_menu) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\vscode\.venv\lib\site-packages (from requests<3,>=2.27->streamlit>=0.63->streamlit_option_menu) (2024.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\vscode\.venv\lib\site-packages (from rich<14,>=10.14.0->streamlit>=0.63->streamlit_option_menu) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\vscode\.venv\lib\site-packages (from rich<14,>=10.14.0->streamlit>=0.63->streamlit_option_menu) (2.17.2)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\vscode\.venv\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit>=0.63->streamlit_option_menu) (5.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\vscode\.venv\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (2.1.5)
Requirement already satisfied: attrs>=22.2.0 in c:\vscode\.venv\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\vscode\.venv\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in c:\vscode\.venv\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (0.34.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\vscode\.venv\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=0.63->streamlit_option_menu) (0.18.0)
Requirement already satisfied: mdurl~=0.1 in c:\vscode\.venv\lib\site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit>=0.63->streamlit_option_menu) (0.1.2)
Requirement already satisfied: six>=1.5 in c:\vscode\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit>=0.63->streamlit_option_menu) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
pip install plotly

Collecting plotlyNote: you may need to restart the kernel to use updated packages.

  Downloading plotly-5.20.0-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: tenacity>=6.2.0 in c:\vscode\.venv\lib\site-packages (from plotly) (8.2.3)
Requirement already satisfied: packaging in c:\vscode\.venv\lib\site-packages (from plotly) (23.2)
Downloading plotly-5.20.0-py3-none-any.whl (15.7 MB)
   ---------------------------------------- 0.0/15.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.7 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.7 MB 234.9 kB/s eta 0:01:07
   ---------------------------------------- 0.1/15.7 MB 409.6 kB/s eta 0:00:39
   ---------------------------------------- 0.1/15.7 MB 409.6 kB/s eta 0:00:39
   ---------------------------------------- 0.1/15.7 MB 409.6 kB/s eta 0:00:39
   ---------------------------------------- 0.1/15.7 MB 409.6 kB/s eta 0:00:39
   ---------------------------------------- 0.1/15.7 MB 409.6 kB/s eta 0:00:39
   ---------------------------------------- 0.1/15.7 MB 409.6 kB/s eta 0:00:39
   ---------------------------------------- 0.2/15.7 MB 262.6 kB/s eta 0:01:00
   ---------------------------------------- 0.2/15.7 MB 262.6 kB/s eta 0:01:00
   ---------------------------------------- 0.2/15.7 MB 262.6 kB/s eta 0:01:00
   ---------------------------------------- 0.2/15.7 MB 262.6 kB/s eta 0:01:00
   ---------------------------------------- 0.2/15.7 MB 262.6 kB/s eta 0:01:00
   ---------------------------------------- 0.2/15.7 MB 262.6 kB/s eta 0:01:00
   ---------------------------------------- 0.2/15.7 MB 262.6 kB/s eta 0:01:00
   ---------------------------------------- 0.2/15.7 MB 262.6 kB/s eta 0:01:00
   ---------------------------------------- 0.2/15.7 MB 262.6 kB/s eta 0:01:00
   ---------------------------------------- 0.2/15.7 MB 262.6 kB/s eta 0:01:00
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.2/15.7 MB 191.7 kB/s eta 0:01:21
    --------------------------------------- 0.3/15.7 MB 116.4 kB/s eta 0:02:13
    --------------------------------------- 0.3/15.7 MB 116.4 kB/s eta 0:02:13
    --------------------------------------- 0.3/15.7 MB 116.4 kB/s eta 0:02:13
    --------------------------------------- 0.3/15.7 MB 116.4 kB/s eta 0:02:13
    --------------------------------------- 0.3/15.7 MB 116.4 kB/s eta 0:02:13
    --------------------------------------- 0.3/15.7 MB 116.4 kB/s eta 0:02:13
    --------------------------------------- 0.3/15.7 MB 116.4 kB/s eta 0:02:13
    --------------------------------------- 0.3/15.7 MB 116.4 kB/s eta 0:02:13
    --------------------------------------- 0.3/15.7 MB 116.4 kB/s eta 0:02:13
    --------------------------------------- 0.3/15.7 MB 116.4 kB/s eta 0:02:13
    --------------------------------------- 0.3/15.7 MB 116.4 kB/s eta 0:02:13
    --------------------------------------- 0.3/15.7 MB 116.4 kB/s eta 0:02:13
    --------------------------------------- 0.3/15.7 MB 116.4 kB/s eta 0:02:13
    --------------------------------------- 0.3/15.7 MB 116.4 kB/s eta 0:02:13
    --------------------------------------- 0.3/15.7 MB 116.4 kB/s eta 0:02:13
    --------------------------------------- 0.3/15.7 MB 116.4 kB/s eta 0:02:13
    --------------------------------------- 0.3/15.7 MB 116.4 kB/s eta 0:02:13
    --------------------------------------- 0.3/15.7 MB 116.4 kB/s eta 0:02:13
    --------------------------------------- 0.3/15.7 MB 116.4 kB/s eta 0:02:13
    --------------------------------------- 0.3/15.7 MB 116.4 kB/s eta 0:02:13
    --------------------------------------- 0.4/15.7 MB 105.1 kB/s eta 0:02:26
    --------------------------------------- 0.4/15.7 MB 105.1 kB/s eta 0:02:26
    --------------------------------------- 0.4/15.7 MB 105.1 kB/s eta 0:02:26
    --------------------------------------- 0.4/15.7 MB 105.1 kB/s eta 0:02:26
    --------------------------------------- 0.4/15.7 MB 105.1 kB/s eta 0:02:26
    --------------------------------------- 0.4/15.7 MB 105.1 kB/s eta 0:02:26
    --------------------------------------- 0.4/15.7 MB 105.1 kB/s eta 0:02:26
    --------------------------------------- 0.4/15.7 MB 105.1 kB/s eta 0:02:26
   - -------------------------------------- 0.4/15.7 MB 105.5 kB/s eta 0:02:25
   - -------------------------------------- 0.4/15.7 MB 105.5 kB/s eta 0:02:25
   - -------------------------------------- 0.4/15.7 MB 105.5 kB/s eta 0:02:25
   - -------------------------------------- 0.4/15.7 MB 105.5 kB/s eta 0:02:25
   - -------------------------------------- 0.4/15.7 MB 105.5 kB/s eta 0:02:25
   - -------------------------------------- 0.4/15.7 MB 105.5 kB/s eta 0:02:25
   - -------------------------------------- 0.4/15.7 MB 105.5 kB/s eta 0:02:25
   - -------------------------------------- 0.4/15.7 MB 105.5 kB/s eta 0:02:25
   - -------------------------------------- 0.4/15.7 MB 105.5 kB/s eta 0:02:25
   - -------------------------------------- 0.4/15.7 MB 105.5 kB/s eta 0:02:25
   - -------------------------------------- 0.4/15.7 MB 105.5 kB/s eta 0:02:25
   - -------------------------------------- 0.4/15.7 MB 105.5 kB/s eta 0:02:25
   - -------------------------------------- 0.5/15.7 MB 103.6 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 103.6 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 103.6 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 103.6 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 103.6 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 103.6 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 103.6 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 103.6 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 103.6 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 103.6 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 103.6 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 103.6 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 103.6 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 103.6 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 103.6 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 103.6 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 103.6 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 103.6 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 103.6 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 102.5 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 102.5 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 102.5 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 102.5 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 102.5 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 102.5 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 102.5 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 102.5 kB/s eta 0:02:28
   - -------------------------------------- 0.5/15.7 MB 102.5 kB/s eta 0:02:28
   - -------------------------------------- 0.6/15.7 MB 104.0 kB/s eta 0:02:26
   - -------------------------------------- 0.6/15.7 MB 104.0 kB/s eta 0:02:26
   - -------------------------------------- 0.6/15.7 MB 104.0 kB/s eta 0:02:26
   - -------------------------------------- 0.6/15.7 MB 104.0 kB/s eta 0:02:26
   - -------------------------------------- 0.6/15.7 MB 104.0 kB/s eta 0:02:26
   - -------------------------------------- 0.6/15.7 MB 104.0 kB/s eta 0:02:26
   - -------------------------------------- 0.6/15.7 MB 104.0 kB/s eta 0:02:26
   - -------------------------------------- 0.6/15.7 MB 104.0 kB/s eta 0:02:26
   - -------------------------------------- 0.7/15.7 MB 111.3 kB/s eta 0:02:16
   - -------------------------------------- 0.7/15.7 MB 111.3 kB/s eta 0:02:16
   - -------------------------------------- 0.7/15.7 MB 111.3 kB/s eta 0:02:16
   - -------------------------------------- 0.7/15.7 MB 111.3 kB/s eta 0:02:16
   - -------------------------------------- 0.7/15.7 MB 111.3 kB/s eta 0:02:16
   - -------------------------------------- 0.7/15.7 MB 111.3 kB/s eta 0:02:16
   - -------------------------------------- 0.7/15.7 MB 114.8 kB/s eta 0:02:11
   - -------------------------------------- 0.7/15.7 MB 118.0 kB/s eta 0:02:07
   - -------------------------------------- 0.7/15.7 MB 118.0 kB/s eta 0:02:07
   - -------------------------------------- 0.7/15.7 MB 118.0 kB/s eta 0:02:07
   - -------------------------------------- 0.7/15.7 MB 118.0 kB/s eta 0:02:07
   -- ------------------------------------- 0.8/15.7 MB 127.6 kB/s eta 0:01:57
   -- ------------------------------------- 0.8/15.7 MB 127.6 kB/s eta 0:01:57
   -- ------------------------------------- 0.8/15.7 MB 127.6 kB/s eta 0:01:57
   -- ------------------------------------- 0.8/15.7 MB 127.6 kB/s eta 0:01:57
   -- ------------------------------------- 0.8/15.7 MB 127.6 kB/s eta 0:01:57
   -- ------------------------------------- 0.8/15.7 MB 127.6 kB/s eta 0:01:57
   -- ------------------------------------- 0.8/15.7 MB 127.6 kB/s eta 0:01:57
   -- ------------------------------------- 0.8/15.7 MB 127.6 kB/s eta 0:01:57
   -- ------------------------------------- 0.8/15.7 MB 127.6 kB/s eta 0:01:57
   -- ------------------------------------- 0.8/15.7 MB 127.6 kB/s eta 0:01:57
   -- ------------------------------------- 0.8/15.7 MB 127.6 kB/s eta 0:01:57
   -- ------------------------------------- 0.8/15.7 MB 127.6 kB/s eta 0:01:57
   -- ------------------------------------- 0.8/15.7 MB 127.6 kB/s eta 0:01:57
   -- ------------------------------------- 0.8/15.7 MB 127.6 kB/s eta 0:01:57
   -- ------------------------------------- 0.9/15.7 MB 124.2 kB/s eta 0:02:00
   -- ------------------------------------- 0.9/15.7 MB 124.2 kB/s eta 0:02:00
   -- ------------------------------------- 0.9/15.7 MB 124.2 kB/s eta 0:02:00
   -- ------------------------------------- 0.9/15.7 MB 124.2 kB/s eta 0:02:00
   -- ------------------------------------- 0.9/15.7 MB 124.2 kB/s eta 0:02:00
   -- ------------------------------------- 0.9/15.7 MB 124.2 kB/s eta 0:02:00
   -- ------------------------------------- 0.9/15.7 MB 124.2 kB/s eta 0:02:00
   -- ------------------------------------- 0.9/15.7 MB 124.2 kB/s eta 0:02:00
   -- ------------------------------------- 0.9/15.7 MB 124.2 kB/s eta 0:02:00
   -- ------------------------------------- 0.9/15.7 MB 124.2 kB/s eta 0:02:00
   -- ------------------------------------- 0.9/15.7 MB 124.2 kB/s eta 0:02:00
   -- ------------------------------------- 0.9/15.7 MB 124.2 kB/s eta 0:02:00
   -- ------------------------------------- 0.9/15.7 MB 117.9 kB/s eta 0:02:06
   -- ------------------------------------- 0.9/15.7 MB 119.9 kB/s eta 0:02:04
   -- ------------------------------------- 0.9/15.7 MB 119.9 kB/s eta 0:02:04
   -- ------------------------------------- 0.9/15.7 MB 120.0 kB/s eta 0:02:03
   -- ------------------------------------- 1.0/15.7 MB 122.7 kB/s eta 0:02:00
   -- ------------------------------------- 1.0/15.7 MB 124.8 kB/s eta 0:01:58
   -- ------------------------------------- 1.0/15.7 MB 126.7 kB/s eta 0:01:56
   -- ------------------------------------- 1.0/15.7 MB 127.2 kB/s eta 0:01:56
   -- ------------------------------------- 1.0/15.7 MB 129.0 kB/s eta 0:01:54
   -- ------------------------------------- 1.1/15.7 MB 131.8 kB/s eta 0:01:51
   -- ------------------------------------- 1.1/15.7 MB 133.9 kB/s eta 0:01:50
   -- ------------------------------------- 1.1/15.7 MB 134.6 kB/s eta 0:01:49
   -- ------------------------------------- 1.1/15.7 MB 138.8 kB/s eta 0:01:45
   --- ------------------------------------ 1.2/15.7 MB 141.2 kB/s eta 0:01:43
   --- ------------------------------------ 1.2/15.7 MB 141.9 kB/s eta 0:01:43
   --- ------------------------------------ 1.2/15.7 MB 146.1 kB/s eta 0:01:40
   --- ------------------------------------ 1.3/15.7 MB 148.6 kB/s eta 0:01:38
   --- ------------------------------------ 1.3/15.7 MB 149.3 kB/s eta 0:01:37
   --- ------------------------------------ 1.3/15.7 MB 151.2 kB/s eta 0:01:36
   --- ------------------------------------ 1.3/15.7 MB 153.6 kB/s eta 0:01:34
   --- ------------------------------------ 1.3/15.7 MB 155.5 kB/s eta 0:01:33
   --- ------------------------------------ 1.4/15.7 MB 157.9 kB/s eta 0:01:31
   --- ------------------------------------ 1.4/15.7 MB 159.7 kB/s eta 0:01:30
   --- ------------------------------------ 1.4/15.7 MB 159.7 kB/s eta 0:01:30
   --- ------------------------------------ 1.4/15.7 MB 161.2 kB/s eta 0:01:29
   --- ------------------------------------ 1.5/15.7 MB 163.8 kB/s eta 0:01:27
   --- ------------------------------------ 1.5/15.7 MB 165.6 kB/s eta 0:01:26
   --- ------------------------------------ 1.5/15.7 MB 166.1 kB/s eta 0:01:26
   --- ------------------------------------ 1.5/15.7 MB 167.3 kB/s eta 0:01:25
   --- ------------------------------------ 1.5/15.7 MB 167.6 kB/s eta 0:01:25
   --- ------------------------------------ 1.6/15.7 MB 170.9 kB/s eta 0:01:23
   --- ------------------------------------ 1.6/15.7 MB 171.5 kB/s eta 0:01:23
   ---- ----------------------------------- 1.6/15.7 MB 174.8 kB/s eta 0:01:21
   ---- ----------------------------------- 1.6/15.7 MB 177.2 kB/s eta 0:01:20
   ---- ----------------------------------- 1.6/15.7 MB 177.7 kB/s eta 0:01:20
   ---- ----------------------------------- 1.7/15.7 MB 181.3 kB/s eta 0:01:18
   ---- ----------------------------------- 1.7/15.7 MB 183.3 kB/s eta 0:01:17
   ---- ----------------------------------- 1.7/15.7 MB 183.8 kB/s eta 0:01:16
   ---- ----------------------------------- 1.8/15.7 MB 187.2 kB/s eta 0:01:15
   ---- ----------------------------------- 1.8/15.7 MB 187.4 kB/s eta 0:01:15
   ---- ----------------------------------- 1.8/15.7 MB 190.0 kB/s eta 0:01:14
   ---- ----------------------------------- 1.8/15.7 MB 191.7 kB/s eta 0:01:13
   ---- ----------------------------------- 1.8/15.7 MB 191.7 kB/s eta 0:01:13
   ---- ----------------------------------- 1.9/15.7 MB 193.3 kB/s eta 0:01:12
   ---- ----------------------------------- 1.9/15.7 MB 195.2 kB/s eta 0:01:11
   ---- ----------------------------------- 1.9/15.7 MB 195.2 kB/s eta 0:01:11
   ---- ----------------------------------- 1.9/15.7 MB 196.4 kB/s eta 0:01:11
   ---- ----------------------------------- 1.9/15.7 MB 196.9 kB/s eta 0:01:10
   ---- ----------------------------------- 1.9/15.7 MB 196.9 kB/s eta 0:01:10
   ---- ----------------------------------- 2.0/15.7 MB 196.1 kB/s eta 0:01:11
   ----- ---------------------------------- 2.0/15.7 MB 198.3 kB/s eta 0:01:10
   ----- ---------------------------------- 2.0/15.7 MB 199.4 kB/s eta 0:01:09
   ----- ---------------------------------- 2.0/15.7 MB 201.1 kB/s eta 0:01:08
   ----- ---------------------------------- 2.0/15.7 MB 201.2 kB/s eta 0:01:08
   ----- ---------------------------------- 2.1/15.7 MB 203.7 kB/s eta 0:01:07
   ----- ---------------------------------- 2.1/15.7 MB 204.1 kB/s eta 0:01:07
   ----- ---------------------------------- 2.1/15.7 MB 205.1 kB/s eta 0:01:07
   ----- ---------------------------------- 2.1/15.7 MB 206.5 kB/s eta 0:01:06
   ----- ---------------------------------- 2.1/15.7 MB 206.5 kB/s eta 0:01:06
   ----- ---------------------------------- 2.2/15.7 MB 207.3 kB/s eta 0:01:06
   ----- ---------------------------------- 2.2/15.7 MB 209.3 kB/s eta 0:01:05
   ----- ---------------------------------- 2.2/15.7 MB 210.3 kB/s eta 0:01:05
   ----- ---------------------------------- 2.2/15.7 MB 210.7 kB/s eta 0:01:04
   ----- ---------------------------------- 2.2/15.7 MB 211.7 kB/s eta 0:01:04
   ----- ---------------------------------- 2.3/15.7 MB 213.0 kB/s eta 0:01:04
   ----- ---------------------------------- 2.3/15.7 MB 214.0 kB/s eta 0:01:03
   ----- ---------------------------------- 2.3/15.7 MB 214.6 kB/s eta 0:01:03
   ----- ---------------------------------- 2.3/15.7 MB 214.6 kB/s eta 0:01:03
   ----- ---------------------------------- 2.3/15.7 MB 215.0 kB/s eta 0:01:03
   ------ --------------------------------- 2.4/15.7 MB 216.6 kB/s eta 0:01:02
   ------ --------------------------------- 2.4/15.7 MB 218.2 kB/s eta 0:01:01
   ------ --------------------------------- 2.4/15.7 MB 219.1 kB/s eta 0:01:01
   ------ --------------------------------- 2.4/15.7 MB 219.1 kB/s eta 0:01:01
   ------ --------------------------------- 2.4/15.7 MB 219.7 kB/s eta 0:01:01
   ------ --------------------------------- 2.5/15.7 MB 221.2 kB/s eta 0:01:00
   ------ --------------------------------- 2.5/15.7 MB 221.2 kB/s eta 0:01:00
   ------ --------------------------------- 2.5/15.7 MB 222.1 kB/s eta 0:01:00
   ------ --------------------------------- 2.5/15.7 MB 222.4 kB/s eta 0:01:00
   ------ --------------------------------- 2.5/15.7 MB 224.2 kB/s eta 0:00:59
   ------ --------------------------------- 2.6/15.7 MB 225.4 kB/s eta 0:00:59
   ------ --------------------------------- 2.6/15.7 MB 225.4 kB/s eta 0:00:59
   ------ --------------------------------- 2.6/15.7 MB 226.2 kB/s eta 0:00:58
   ------ --------------------------------- 2.6/15.7 MB 226.2 kB/s eta 0:00:58
   ------ --------------------------------- 2.7/15.7 MB 228.8 kB/s eta 0:00:57

In [58]:
pip install nbformat --upgrade

Collecting nbformat
  Downloading nbformat-5.10.3-py3-none-any.whl.metadata (3.6 kB)
Collecting fastjsonschema (from nbformat)
  Downloading fastjsonschema-2.19.1-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: jsonschema>=2.6 in c:\vscode\.venv\lib\site-packages (from nbformat) (4.21.1)
Requirement already satisfied: jupyter-core in c:\vscode\.venv\lib\site-packages (from nbformat) (5.7.2)
Requirement already satisfied: traitlets>=5.1 in c:\vscode\.venv\lib\site-packages (from nbformat) (5.14.2)
Requirement already satisfied: attrs>=22.2.0 in c:\vscode\.venv\lib\site-packages (from jsonschema>=2.6->nbformat) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\vscode\.venv\lib\site-packages (from jsonschema>=2.6->nbformat) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in c:\vscode\.venv\lib\site-packages (from jsonschema>=2.6->nbformat) (0.34.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\vscode\.venv\lib\site-packages (from jsonschema>=2.6->nbformat) (0.18.0)
Requirement already satisfied: platformdirs>=2.5 in c:\vscode\.venv\lib\site-packages (from jupyter-core->nbformat) (4.2.0)
Requirement already satisfied: pywin32>=300 in c:\vscode\.venv\lib\site-packages (from jupyter-core->nbformat) (306)
Downloading nbformat-5.10.3-py3-none-any.whl (78 kB)
   ---------------------------------------- 0.0/78.4 kB ? eta -:--:--
   --------------- ------------------------ 30.7/78.4 kB 1.4 MB/s eta 0:00:01
   -------------------- ------------------- 41.0/78.4 kB 495.5 kB/s eta 0:00:01
   ---------------------------------------- 78.4/78.4 kB 725.5 kB/s eta 0:00:00
Downloading fastjsonschema-2.19.1-py3-none-any.whl (23 kB)
Installing collected packages: fastjsonschema, nbformat
Successfully installed fastjsonschema-2.19.1 nbformat-5.10.3
Note: you may need to restart the kernel to use updated packages.

In [59]:
pip install plotly

Requirement already satisfied: plotly in c:\vscode\.venv\lib\site-packages (5.20.0)
Requirement already satisfied: tenacity>=6.2.0 in c:\vscode\.venv\lib\site-packages (from plotly) (8.2.3)
Requirement already satisfied: packaging in c:\vscode\.venv\lib\site-packages (from plotly) (23.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
import psycopg2
import json
import git
import pandas as pd
from streamlit_option_menu import option_menu
import plotly.express as px

In [3]:
#aggregated_insurance

path1= "C:/Users/Anusha Badami/Desktop/Phonepe/Phonepe/data/aggregated/transaction/country/india/state/"

agg_insur_list= os.listdir(path1)

columns1= {"States":[], "Years":[], "Quarter":[], "Insurance_type":[], "Insurance_count":[],"Insurance_amount":[] }

for state in agg_insur_list:
    cur_states =path1+state+"/"
    agg_year_list = os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_years = cur_states+year+"/"
        agg_file_list = os.listdir(cur_years)

        for file in agg_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            A = json.load(data)

            for i in A["data"]["transactionData"]:
                name = i["name"]
                count = i["paymentInstruments"][0]["count"]
                amount = i["paymentInstruments"][0]["amount"]
                columns1["Insurance_type"].append(name)
                columns1["Insurance_count"].append(count)
                columns1["Insurance_amount"].append(amount)
                columns1["States"].append(state)
                columns1["Years"].append(year)
                columns1["Quarter"].append(int(file.strip(".json")))

In [4]:
aggre_insurance=pd.DataFrame(columns1)

aggre_insurance["States"] = aggre_insurance["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
aggre_insurance["States"] = aggre_insurance["States"].str.replace("-"," ")
aggre_insurance["States"] = aggre_insurance["States"].str.title()
aggre_insurance['States'] = aggre_insurance['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [5]:
aggre_insurance

,States,Years,Quarter,Insurance_type,Insurance_count,Insurance_amount
0,Andaman & Nicobar,2018,1,Recharge & bill payments,4200,1.845307e+06
1,Andaman & Nicobar,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,Andaman & Nicobar,2018,1,Merchant payments,298,4.525072e+05
3,Andaman & Nicobar,2018,1,Financial Services,33,1.060142e+04
4,Andaman & Nicobar,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
4309,West Bengal,2023,4,Merchant payments,354067997,2.390738e+11
4310,West Bengal,2023,4,Peer-to-peer payments,317959249,9.641385e+11
4311,West Bengal,2023,4,Recharge & bill payments,64920775,4.531943e+10
4312,West Bengal,2023,4,Financial Services,480740,4.590073e+08
4313,West Bengal,2023,4,Others,524477,4.041567e+08

In [6]:
#aggregated_transaction

path2="C:/Users/Anusha Badami/Desktop/Phonepe/Phonepe/data/aggregated/transaction/country/india/state/"
agg_tran_list=os.listdir(path2)


columns2 ={"States":[], "Years":[], "Quarter":[], "Transaction_type":[], "Transaction_count":[],"Transaction_amount":[] }

for state in agg_tran_list:
    cur_states =path2+state+"/"
    agg_year_list = os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_years = cur_states+year+"/"
        agg_file_list = os.listdir(cur_years)

        for file in agg_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            B = json.load(data)

            for i in B["data"]["transactionData"]:
                name = i["name"]
                count = i["paymentInstruments"][0]["count"]
                amount = i["paymentInstruments"][0]["amount"]
                columns2["Transaction_type"].append(name)
                columns2["Transaction_count"].append(count)
                columns2["Transaction_amount"].append(amount)
                columns2["States"].append(state)
                columns2["Years"].append(year)
                columns2["Quarter"].append(int(file.strip(".json")))

In [7]:
aggre_transaction=pd.DataFrame(columns2)

aggre_transaction["States"] = aggre_transaction["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
aggre_transaction["States"] = aggre_transaction["States"].str.replace("-"," ")
aggre_transaction["States"] = aggre_transaction["States"].str.title()
aggre_transaction['States'] = aggre_transaction['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [8]:
aggre_transaction

,States,Years,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2018,1,Recharge & bill payments,4200,1.845307e+06
1,Andaman & Nicobar,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,Andaman & Nicobar,2018,1,Merchant payments,298,4.525072e+05
3,Andaman & Nicobar,2018,1,Financial Services,33,1.060142e+04
4,Andaman & Nicobar,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
4309,West Bengal,2023,4,Merchant payments,354067997,2.390738e+11
4310,West Bengal,2023,4,Peer-to-peer payments,317959249,9.641385e+11
4311,West Bengal,2023,4,Recharge & bill payments,64920775,4.531943e+10
4312,West Bengal,2023,4,Financial Services,480740,4.590073e+08
4313,West Bengal,2023,4,Others,524477,4.041567e+08

In [10]:
#aggregated user

path3 = "C:/Users/Anusha Badami/Desktop/Phonepe/Phonepe/data/aggregated/user/country/india/state/"
         
agg_user_list = os.listdir(path3)

columns3 = {"States":[], "Years":[], "Quarter":[], "Brands":[],"Transaction_count":[], "Percentage":[]}

for state in agg_user_list:
    cur_states = path3+state+"/"
    agg_year_list = os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_years = cur_states+year+"/"
        agg_file_list = os.listdir(cur_years)
        
        for file in agg_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            C = json.load(data)

            try:

                for i in C["data"]["usersByDevice"]:
                    brand = i["brand"]
                    count = i["count"]
                    percentage = i["percentage"]
                    columns3["Brands"].append(brand)
                    columns3["Transaction_count"].append(count)
                    columns3["Percentage"].append(percentage)
                    columns3["States"].append(state)
                    columns3["Years"].append(year)
                    columns3["Quarter"].append(int(file.strip(".json")))
            
            except:
                pass

In [11]:
aggre_user=pd.DataFrame(columns3)

aggre_user["States"] = aggre_user["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
aggre_user["States"] = aggre_user["States"].str.replace("-"," ")
aggre_user["States"] = aggre_user["States"].str.title()
aggre_user['States'] = aggre_user['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [12]:
aggre_user

                 States Years  Quarter   Brands  Transaction_count  Percentage
0     Andaman & Nicobar  2018        1   Xiaomi               1665    0.247033
1     Andaman & Nicobar  2018        1  Samsung               1445    0.214392
2     Andaman & Nicobar  2018        1     Vivo                982    0.145697
3     Andaman & Nicobar  2018        1     Oppo                501    0.074332
4     Andaman & Nicobar  2018        1  OnePlus                332    0.049258
...                 ...   ...      ...      ...                ...         ...
6727        West Bengal  2022        1   Lenovo             330017    0.015056
6728        West Bengal  2022        1  Infinix             284678    0.012987
6729        West Bengal  2022        1     Asus             280347    0.012790
6730        West Bengal  2022        1    Apple             277752    0.012671
6731        West Bengal  2022        1   Others            2196334    0.100199

[6732 rows x 6 columns]

In [13]:
#map_insurance

path4= "C:/Users/Anusha Badami/Desktop/Phonepe/Phonepe/data/map/insurance/hover/country/india/state/"

map_insur_list= os.listdir(path4)

columns4= {"States":[], "Years":[], "Quarter":[], "Districts":[], "Transaction_count":[],"Transaction_amount":[] }

for state in map_insur_list:
    cur_states =path4+state+"/"
    agg_year_list = os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_years = cur_states+year+"/"
        agg_file_list = os.listdir(cur_years)

        for file in agg_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            D = json.load(data)

            for i in D["data"]["hoverDataList"]:
                name = i["name"]
                count = i["metric"][0]["count"]
                amount = i["metric"][0]["amount"]
                columns4["Districts"].append(name)
                columns4["Transaction_count"].append(count)
                columns4["Transaction_amount"].append(amount)
                columns4["States"].append(state)
                columns4["Years"].append(year)
                columns4["Quarter"].append(int(file.strip(".json")))

In [14]:
map_insurance=pd.DataFrame(columns4)

map_insurance["States"] = map_insurance["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
map_insurance["States"] = map_insurance["States"].str.replace("-"," ")
map_insurance["States"] = map_insurance["States"].str.title()
map_insurance['States'] = map_insurance['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [15]:
map_insurance

,States,Years,Quarter,Districts,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2020,2,south andaman district,3,795.0
1,Andaman & Nicobar,2020,2,nicobars district,3,565.0
2,Andaman & Nicobar,2020,3,north and middle andaman district,1,281.0
3,Andaman & Nicobar,2020,3,south andaman district,35,13651.0
4,Andaman & Nicobar,2020,3,nicobars district,5,1448.0
...,...,...,...,...,...,...
10823,West Bengal,2023,4,nadia district,2786,4012958.0
10824,West Bengal,2023,4,birbhum district,1162,1720043.0
10825,West Bengal,2023,4,purba medinipur district,2507,3400040.0
10826,West Bengal,2023,4,maldah district,2886,3998317.0
10827,West Bengal,2023,4,darjiling district,2762,4044883.0

In [16]:
#map transaction

path5="C:/Users/Anusha Badami/Desktop/Phonepe/Phonepe/data/map/transaction/hover/country/india/state/"
map_tran_list = os.listdir(path5)

columns5 = {"States":[], "Years":[], "Quarter":[],"District":[], "Transaction_count":[],"Transaction_amount":[]}

for state in map_tran_list:
    cur_states = path5+state+"/"
    map_year_list = os.listdir(cur_states)
    
    for year in map_year_list:
        cur_years = cur_states+year+"/"
        map_file_list = os.listdir(cur_years)
        
        for file in map_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            E = json.load(data)

            for i in E['data']["hoverDataList"]:
                name = i["name"]
                count = i["metric"][0]["count"]
                amount = i["metric"][0]["amount"]
                columns5["District"].append(name)
                columns5["Transaction_count"].append(count)
                columns5["Transaction_amount"].append(amount)
                columns5["States"].append(state)
                columns5["Years"].append(year)
                columns5["Quarter"].append(int(file.strip(".json")))

In [17]:
map_transaction=pd.DataFrame(columns5)

map_transaction["States"] = map_transaction["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
map_transaction["States"] = map_transaction["States"].str.replace("-"," ")
map_transaction["States"] = map_transaction["States"].str.title()
map_transaction['States'] = map_transaction['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [18]:
map_transaction

,States,Years,Quarter,District,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2018,1,north and middle andaman district,442,9.316631e+05
1,Andaman & Nicobar,2018,1,south andaman district,5688,1.256025e+07
2,Andaman & Nicobar,2018,1,nicobars district,528,1.139849e+06
3,Andaman & Nicobar,2018,2,north and middle andaman district,825,1.317863e+06
4,Andaman & Nicobar,2018,2,south andaman district,9395,2.394824e+07
...,...,...,...,...,...,...
17559,West Bengal,2023,4,nadia district,36242432,6.879568e+10
17560,West Bengal,2023,4,birbhum district,20708496,3.690499e+10
17561,West Bengal,2023,4,purba medinipur district,40572042,7.981990e+10
17562,West Bengal,2023,4,maldah district,34654950,6.416729e+10
17563,West Bengal,2023,4,darjiling district,16807885,2.793986e+10

In [19]:
#map_user

path6 = "C:/Users/Anusha Badami/Desktop/Phonepe/Phonepe/data/map/user/hover/country/india/state/"
map_user_list = os.listdir(path6)

columns6 = {"States":[], "Years":[], "Quarter":[], "Districts":[], "RegisteredUser":[], "AppOpens":[]}

for state in map_user_list:
    cur_states = path6+state+"/"
    map_year_list = os.listdir(cur_states)
    
    for year in map_year_list:
        cur_years = cur_states+year+"/"
        map_file_list = os.listdir(cur_years)
        
        for file in map_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            F = json.load(data)

            for i in F["data"]["hoverData"].items():
                district = i[0]
                registereduser = i[1]["registeredUsers"]
                appopens = i[1]["appOpens"]
                columns6["Districts"].append(district)
                columns6["RegisteredUser"].append(registereduser)
                columns6["AppOpens"].append(appopens)
                columns6["States"].append(state)
                columns6["Years"].append(year)
                columns6["Quarter"].append(int(file.strip(".json")))

In [21]:
map_user=pd.DataFrame(columns6)

map_user["States"] = map_user["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
map_user["States"] = map_user["States"].str.replace("-"," ")
map_user["States"] = map_user["States"].str.title()
map_user['States'] = map_user['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [22]:
map_user

,States,Years,Quarter,Districts,RegisteredUser,AppOpens
0,Andaman & Nicobar,2018,1,north and middle andaman district,632,0
1,Andaman & Nicobar,2018,1,south andaman district,5846,0
2,Andaman & Nicobar,2018,1,nicobars district,262,0
3,Andaman & Nicobar,2018,2,north and middle andaman district,911,0
4,Andaman & Nicobar,2018,2,south andaman district,8143,0
...,...,...,...,...,...,...
17563,West Bengal,2023,4,nadia district,1603527,67224546
17564,West Bengal,2023,4,birbhum district,1013025,52281841
17565,West Bengal,2023,4,purba medinipur district,1589203,69991821
17566,West Bengal,2023,4,maldah district,1134600,88292475
17567,West Bengal,2023,4,darjiling district,660231,39079247

In [23]:
#top_insurance

path7 = "C:/Users/Anusha Badami/Desktop/Phonepe/Phonepe/data/top/insurance/country/india/state/"

top_insur_list = os.listdir(path7)

columns7 = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}

for state in top_insur_list:
    cur_states = path7+state+"/"
    top_year_list = os.listdir(cur_states)

    for year in top_year_list:
        cur_years = cur_states+year+"/"
        top_file_list = os.listdir(cur_years)

        for file in top_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            G = json.load(data)

            for i in G["data"]["pincodes"]:
                entityName = i["entityName"]
                count = i["metric"]["count"]
                amount = i["metric"]["amount"]
                columns7["Pincodes"].append(entityName)
                columns7["Transaction_count"].append(count)
                columns7["Transaction_amount"].append(amount)
                columns7["States"].append(state)
                columns7["Years"].append(year)
                columns7["Quarter"].append(int(file.strip(".json")))

In [26]:
top_insurance=pd.DataFrame(columns7)

top_insurance["States"] = top_insurance["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
top_insurance["States"] = top_insurance["States"].str.replace("-"," ")
top_insurance["States"] = top_insurance["States"].str.title()
top_insurance['States'] = top_insurance['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [27]:
top_insurance

,States,Years,Quarter,Pincodes,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2020,2,744301,3,565.0
1,Andaman & Nicobar,2020,2,744104,2,513.0
2,Andaman & Nicobar,2020,2,744101,1,282.0
3,Andaman & Nicobar,2020,3,744112,9,3432.0
4,Andaman & Nicobar,2020,3,744105,7,3948.0
...,...,...,...,...,...,...
5244,West Bengal,2023,4,700135,556,939622.0
5245,West Bengal,2023,4,700091,535,767163.0
5246,West Bengal,2023,4,700015,521,683025.0
5247,West Bengal,2023,4,700059,518,843045.0
5248,West Bengal,2023,4,711102,517,769517.0

In [28]:
#top_transaction

path8 = "C:/Users/Anusha Badami/Desktop/Phonepe/Phonepe/data/top/transaction/country/india/state/"
top_tran_list = os.listdir(path8)

columns8 = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}

for state in top_tran_list:
    cur_states = path8+state+"/"
    top_year_list = os.listdir(cur_states)
    
    for year in top_year_list:
        cur_years = cur_states+year+"/"
        top_file_list = os.listdir(cur_years)
        
        for file in top_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            H = json.load(data)

            for i in H["data"]["pincodes"]:
                entityName = i["entityName"]
                count = i["metric"]["count"]
                amount = i["metric"]["amount"]
                columns8["Pincodes"].append(entityName)
                columns8["Transaction_count"].append(count)
                columns8["Transaction_amount"].append(amount)
                columns8["States"].append(state)
                columns8["Years"].append(year)
                columns8["Quarter"].append(int(file.strip(".json")))

In [29]:
top_transaction=pd.DataFrame(columns8)

top_transaction["States"] = top_transaction["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
top_transaction["States"] = top_transaction["States"].str.replace("-"," ")
top_transaction["States"] = top_transaction["States"].str.title()
top_transaction['States'] = top_transaction['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [30]:
top_transaction

,States,Years,Quarter,Pincodes,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2018,1,744101,1622,2.769298e+06
1,Andaman & Nicobar,2018,1,744103,1223,2.238042e+06
2,Andaman & Nicobar,2018,1,744102,969,3.519060e+06
3,Andaman & Nicobar,2018,1,744105,685,1.298561e+06
4,Andaman & Nicobar,2018,1,744104,340,1.039715e+06
...,...,...,...,...,...,...
8562,West Bengal,2023,4,721301,4133775,5.718222e+09
8563,West Bengal,2023,4,700001,3983241,8.039689e+09
8564,West Bengal,2023,4,732125,3950411,6.557345e+09
8565,West Bengal,2023,4,700039,3742452,5.608622e+09
8566,West Bengal,2023,4,700014,3652710,6.184795e+09

In [31]:
#top_user

path9 = "C:/Users/Anusha Badami/Desktop/Phonepe/Phonepe/data/top/user/country/india/state/"
top_user_list = os.listdir(path9)

columns9 = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "RegisteredUser":[]}

for state in top_user_list:
    cur_states = path9+state+"/"
    top_year_list = os.listdir(cur_states)

    for year in top_year_list:
        cur_years = cur_states+year+"/"
        top_file_list = os.listdir(cur_years)

        for file in top_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            I = json.load(data)

            for i in I["data"]["pincodes"]:
                name = i["name"]
                registeredusers = i["registeredUsers"]
                columns9["Pincodes"].append(name)
                columns9["RegisteredUser"].append(registereduser)
                columns9["States"].append(state)
                columns9["Years"].append(year)
                columns9["Quarter"].append(int(file.strip(".json")))

In [32]:
top_user=pd.DataFrame(columns9)

top_user["States"] = top_user["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
top_user["States"] = top_user["States"].str.replace("-"," ")
top_user["States"] = top_user["States"].str.title()
top_user['States'] = top_user['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [33]:
top_user

                 States Years  Quarter Pincodes  RegisteredUser
0     Andaman & Nicobar  2018        1   744103          660231
1     Andaman & Nicobar  2018        1   744101          660231
2     Andaman & Nicobar  2018        1   744105          660231
3     Andaman & Nicobar  2018        1   744102          660231
4     Andaman & Nicobar  2018        1   744104          660231
...                 ...   ...      ...      ...             ...
8563        West Bengal  2023        4   700015          660231
8564        West Bengal  2023        4   742304          660231
8565        West Bengal  2023        4   721101          660231
8566        West Bengal  2023        4   700150          660231
8567        West Bengal  2023        4   700091          660231

[8568 rows x 5 columns]

In [34]:
#Table Creation
#pgsql connection
mydb = psycopg2.connect(host = "localhost",
                        user = "postgres",
                        password = "anushabadami",
                        database = "phonepe",
                        port = "5432"
                        )
cursor = mydb.cursor()

In [35]:
#aggregated insurance table

create_query1= '''CREATE TABLE if not exists aggregated_insurance (States varchar(50),
                                                                      Years int,
                                                                      Quarter int,
                                                                      Insurance_type varchar(50),
                                                                      Insurance_count bigint,
                                                                      Insurance_amount bigint
                                                                      )'''
cursor.execute(create_query1)
mydb.commit()

for index,row in aggre_insurance.iterrows():
    insert_query1 = '''INSERT INTO aggregated_insurance (States, Years, Quarter, Insurance_type, Insurance_count, Insurance_amount)
                                                        values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Insurance_type"],
              row["Insurance_count"],
              row["Insurance_amount"]
              )
    cursor.execute(insert_query1,values)
    mydb.commit()

In [36]:
#aggregated transaction table

create_query2 = '''CREATE TABLE if not exists aggregated_transaction (States varchar(50),
                                                                      Years int,
                                                                      Quarter int,
                                                                      Transaction_type varchar(50),
                                                                      Transaction_count bigint,
                                                                      Transaction_amount bigint
                                                                      )'''
cursor.execute(create_query2)
mydb.commit()

for index,row in aggre_transaction.iterrows():
    insert_query2 = '''INSERT INTO aggregated_transaction (States, Years, Quarter, Transaction_type, Transaction_count, Transaction_amount)
                                                        values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Transaction_type"],
              row["Transaction_count"],
              row["Transaction_amount"]
              )
    cursor.execute(insert_query2,values)
    mydb.commit()

In [37]:

#aggregated user table

create_query3 = '''CREATE TABLE if not exists aggregated_user (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                Brands varchar(50),
                                                                Transaction_count bigint,
                                                                Percentage float)'''
cursor.execute(create_query3)
mydb.commit()

for index,row in aggre_user.iterrows():
    insert_query3 = '''INSERT INTO aggregated_user (States, Years, Quarter, Brands, Transaction_count, Percentage)
                                                    values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Brands"],
              row["Transaction_count"],
              row["Percentage"])
    cursor.execute(insert_query3,values)
    mydb.commit()

In [38]:
#map_insurance_table

create_query4 = '''CREATE TABLE if not exists map_insurance (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                District varchar(50),
                                                                Transaction_count bigint,
                                                                Transaction_amount float)'''
cursor.execute(create_query4)
mydb.commit()

for index,row in map_insurance.iterrows():
            insert_query4 = '''
                INSERT INTO map_insurance (States, Years, Quarter, District, Transaction_count, Transaction_amount)
                VALUES (%s, %s, %s, %s, %s, %s)

            '''
            values = (
                row['States'],
                row['Years'],
                row['Quarter'],
                row['Districts'],
                row['Transaction_count'],
                row['Transaction_amount']
            )
            cursor.execute(insert_query4,values)
            mydb.commit()

In [39]:
#map_transaction_table

create_query5 = '''CREATE TABLE if not exists map_transaction (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                District varchar(50),
                                                                Transaction_count bigint,
                                                                Transaction_amount float)'''
cursor.execute(create_query5)
mydb.commit()

for index,row in map_transaction.iterrows():
            insert_query5 = '''
                INSERT INTO map_Transaction (States, Years, Quarter, District, Transaction_count, Transaction_amount)
                VALUES (%s, %s, %s, %s, %s, %s)

            '''
            values = (
                row['States'],
                row['Years'],
                row['Quarter'],
                row['District'],
                row['Transaction_count'],
                row['Transaction_amount']
            )
            cursor.execute(insert_query5,values)
            mydb.commit()

In [40]:
#map_user_table

create_query6 = '''CREATE TABLE if not exists map_user (States varchar(50),
                                                        Years int,
                                                        Quarter int,
                                                        Districts varchar(50),
                                                        RegisteredUser bigint,
                                                        AppOpens bigint)'''
cursor.execute(create_query6)
mydb.commit()

for index,row in map_user.iterrows():
    insert_query6 = '''INSERT INTO map_user (States, Years, Quarter, Districts, RegisteredUser, AppOpens)
                        values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Districts"],
              row["RegisteredUser"],
              row["AppOpens"])
    cursor.execute(insert_query6,values)
    mydb.commit()

In [41]:
#top_insurance_table

create_query7 = '''CREATE TABLE if not exists top_insurance (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                Pincodes int,
                                                                Transaction_count bigint,
                                                                Transaction_amount bigint)'''
cursor.execute(create_query7)
mydb.commit()

for index,row in top_insurance.iterrows():
    insert_query7 = '''INSERT INTO top_insurance (States, Years, Quarter, Pincodes, Transaction_count, Transaction_amount)
                                                    values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Pincodes"],
              row["Transaction_count"],
              row["Transaction_amount"])
    cursor.execute(insert_query7,values)
    mydb.commit()

In [42]:

#top_transaction_table

create_query8 = '''CREATE TABLE if not exists top_transaction (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                pincodes int,
                                                                Transaction_count bigint,
                                                                Transaction_amount bigint)'''
cursor.execute(create_query8)
mydb.commit()

for index,row in top_transaction.iterrows():
    insert_query8 = '''INSERT INTO top_transaction (States, Years, Quarter, Pincodes, Transaction_count, Transaction_amount)
                                                    values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Pincodes"],
              row["Transaction_count"],
              row["Transaction_amount"])
    cursor.execute(insert_query8,values)
    mydb.commit()

In [43]:
#top_user_table

create_query9 = '''CREATE TABLE if not exists top_user (States varchar(50),
                                                        Years int,
                                                        Quarter int,
                                                        Pincodes int,
                                                        RegisteredUser bigint
                                                        )'''
cursor.execute(create_query9)
mydb.commit()

for index,row in top_user.iterrows():
    insert_query9 = '''INSERT INTO top_user (States, Years, Quarter, Pincodes, RegisteredUser)
                                            values(%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Pincodes"],
              row["RegisteredUser"])
    cursor.execute(insert_query9,values)
    mydb.commit()

In [44]:
#CREATE DATAFRAMES FROM SQL
#sql connection
mydb = psycopg2.connect(host = "localhost",
                        user = "postgres",
                        password = "anushabadami",
                        database = "phonepe",
                        port = "5432"
                        )
cursor = mydb.cursor()

In [45]:
#Aggregated_insurance
cursor.execute("select * from aggregated_insurance;")
mydb.commit()
table1 = cursor.fetchall()

Aggre_insurance = pd.DataFrame(table1,columns = ("States", "Years", "Quarter", "Transaction_type", "Transaction_count","Transaction_amount"))

In [46]:


#Aggregated_transsaction
cursor.execute("select * from aggregated_transaction;")
mydb.commit()
table2 = cursor.fetchall()
Aggre_transaction = pd.DataFrame(table2,columns = ("States", "Years", "Quarter", "Transaction_type", "Transaction_count", "Transaction_amount"))

In [47]:


#Aggregated_user
cursor.execute("select * from aggregated_user")
mydb.commit()
table3 = cursor.fetchall()
Aggre_user = pd.DataFrame(table3,columns = ("States", "Years", "Quarter", "Brands", "Transaction_count", "Percentage"))

In [48]:


#Map_insurance
cursor.execute("select * from map_insurance")
mydb.commit()
table4 = cursor.fetchall()

Map_insurance = pd.DataFrame(table4,columns = ("States", "Years", "Quarter", "Districts", "Transaction_count","Transaction_amount"))

In [49]:

#Map_transaction
cursor.execute("select * from map_transaction")
mydb.commit()
table5= cursor.fetchall()
Map_transaction = pd.DataFrame(table5,columns = ("States", "Years", "Quarter", "Districts", "Transaction_count", "Transaction_amount"))

In [50]:
#Map_user
cursor.execute("select * from map_user")
mydb.commit()
table6 = cursor.fetchall()
Map_user = pd.DataFrame(table6,columns = ("States", "Years", "Quarter", "Districts", "RegisteredUser", "AppOpens"))

In [51]:

#Top_insurance
cursor.execute("select * from top_insurance")
mydb.commit()
table7 = cursor.fetchall()

Top_insurance = pd.DataFrame(table7,columns = ("States", "Years", "Quarter", "Pincodes", "Transaction_count", "Transaction_amount"))

In [52]:
#Top_transaction
cursor.execute("select * from top_transaction")
mydb.commit()
table8 = cursor.fetchall()
Top_transaction = pd.DataFrame(table8,columns = ("States", "Years", "Quarter", "Pincodes", "Transaction_count", "Transaction_amount"))

In [53]:
#Top_user
cursor.execute("select * from top_user")
mydb.commit()
table9 = cursor.fetchall()
Top_user = pd.DataFrame(table9, columns = ("States", "Years", "Quarter", "Pincodes", "RegisteredUser"))